# Site settings
title: "seedubjay"
subtitle: "computer science for everyone"
author: "Charles Jameson"
description: "computer science for everyone"
# keywords: ""

url: "https://seedubjay.com"

exclude:
  - Gemfile
  - Gemfile.lock
  - scripts/

collections:
  projects:
    listed: true
    output: true
    permalink: /:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap

sass:
    sass_dir: assets/css
    style: compressed

feed:
  excerpt_only: true

defaults:
  -
    scope:
      path: "assets/*"
    values:
      sitemap: false

# twitter_username:
mail_address: charleswjameson@gmail.com
github_username: seedubjay
# facebook_username: 

date_format: "%-d %B %Y"

markdown: kramdown
highlighter: rouge
permalink: /blog/:title/