# Site settings
title: "seedubjay"
subtitle: "computer science for people with better things to do"
author: "Charles Jameson"
description: "computer science for people with better things to do"
# keywords: ""

url: "https:/seedubjay.com"

plugins:
  - jekyll-feed
  - jekyll-sitemap

defaults:
  -
    scope:
      path: "assets/*"
    values:
      sitemap: false

# twitter_username:
mail_address: charleswjameson@gmail.com
github_username: seedubjay
# facebook_username: 

date_format: "%-d %B %Y"

markdown: kramdown
highlighter: rouge
permalink: /blog/:title/